esphome:
  name: esphome-web-df046c
  friendly_name: Bedroom Curtains

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "hHEfukk+V0sxssW+QvImOaZa5zXmNLpJWlFLK4C8xkw="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-Df046C"
    password: "AuBdTbjJVkDi"

captive_portal:
    
stepper:
  - platform: a4988
    id: my_stepper
    step_pin: GPIO27
    dir_pin: GPIO26
    max_speed: 10000 steps/s

    # Optional:
    sleep_pin: 
      number: GPIO25
      inverted: true  
    # acceleration: inf
    # deceleration: inf

cover:
  - platform: endstop
    name: "Endstop Cover"

    open_action:
    - stepper.report_position:
        id: my_stepper
        position: 1000000
    - stepper.set_target:
        id: my_stepper
        target: 2000000

    open_duration: 2min
    open_endstop: open_endstop_binary_sensor

    close_action:
    - stepper.report_position:
        id: my_stepper
        position: 1000000
    - stepper.set_target:
            id: my_stepper
            target: 0

    close_duration: 2min
    close_endstop: close_endstop_binary_sensor

    stop_action:
      - stepper.set_target:
          id: my_stepper
          target: !lambda return id(my_stepper).current_position;  

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO32
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Bedroom Curtains Open Endstop"
    device_class: window
    id: open_endstop_binary_sensor

  - platform: gpio
    pin:
      number: GPIO33
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Bedroom Curtains Closed Endstop"
    device_class: window
    id: close_endstop_binary_sensor


# switch:
#   - platform: gpio
#     pin: GPIO32
#     name: "Curtains Open"
#     id: open_cover_switch

#   - platform: gpio
#     pin: GPIO33
#     name: "Curtains Close"
#     id: close_cover_switch